org: solomon
app: simple-store
service: simple-store

provider:
  name: aws
  runtime: nodejs20.x

functions:
  store:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: ANY
